development:
    driver:     mysql
    host:       localhost
    port:       27001
    database:   db_auth
    user:       root
    password:   Pa$$w0rd

production:
    driver:     mysql
    host:       localhost
    port:       27001
    database:   my_project
    user:       root
    password:   Pa$$w0rd